### ISSUE TITLE
Beta release

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc#282]
What should the criteria be to move this forward into beta?

**Comment by fonnesbeck** [comment]
I guess we need to decide which of the v.3 issues need to be taken care of. I think having a solid draft of the docs should be one hurdle. I've already put a skeleton of them in the repo, but they are mostly unwritten.

**Comment by jsalvatier** [comment]
Lets try to push this. Docs is one item.

Since NUTS is often finicky even for small models, we need decent support for metropolis I think. How are we in that department?

**Comment by twiecki** [comment]
I added a milestone Version 3.0.beta and put some issues under it, please add more as you see fit.

Also, we used to have a v3 label which somehow disappeared and I recreated.

**Comment by jsalvatier** [comment]
Do we have any items that should be solved before we do a beta release? I don't think there is anything much. Perhaps we need to change the docs for the automatic transforms and missing variables.

**Comment by twiecki** [comment]
I'm all for going beta.

On Wed, Jun 10, 2015 at 10:42 PM, John Salvatier notifications@github.com
wrote:

> Do we have any items that should be solved before we do a beta release?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/issues/282#issuecomment-110906784.

## 

Thomas Wiecki, PhD
Data Science Lead, Quantopian Inc, Boston

**Comment by jsalvatier** [comment]
@fonnesbeck any blockers for Beta? I think we should announce it in the next few days.

**Comment by fonnesbeck** [comment]
I think beta is an appropriate tag at this point. I still have issues, but nothing I would call "blockers".

**Comment by twiecki** [comment]
Done!
