### ISSUE TITLE
Update example gallery style and formatting

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc#5460]
This is pertinent to pymc-examples. The contributing guide you should read is [this one](https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md) and the repo to fork is https://github.com/pymc-devs/pymc-examples. I am posting here for visibility and to centralize all sprint related issues. 

An overview of the changes, their importance and how to go about them is available at https://pymc-data-umbrella.xyz/en/latest/webinars/contributing_to_documentation/index.html. There you'll find
* A video webinar explaining the material
* A document with all the material covered in the webinar and examples of the changes you have to do to the notebooks.

The progress of updates and notebooks available for updating are available at the [status tracker](https://github.com/pymc-devs/pymc-examples/projects/1). The goal of this issue is to bring notebooks to the "Book style" state (hence the "docs" but no "v4" label), you don't need to run the notebook, only update the markdown cells.

To work on this, go to the [status tracker](https://github.com/pymc-devs/pymc-examples/projects/1) and choose an issue in one of the first three columns. Once you have chosen, you have to visit the issue to check nobody else is working on it and if it is available, comment you plan to work on this and update it to "Book style" column.

**Comment by soma2000-lang** [comment]
I am working on this@OriolAbril

**Comment by OriolAbril** [comment]
Great @soma2000-lang thanks for joining the effort! You should also comment on the issue labeled "tracker id" that corresponds to the notebook you are working on. This way we can avoid duplicated work and ensure there'll be no conflicts and your PR to pymc-examples will be merged. The [status tracker](https://github.com/pymc-devs/pymc-examples/projects/1) linked above has all the tracker issues classified in columns

**Comment by soma2000-lang** [comment]
Ok

**Comment by OriolAbril** [comment]
@soma2000-lang I haven't seen any comment in the issues at pymc-examples, just checking I haven't missed your comment. Please let me know and share the link in a comment here if I have.

**Comment by ricardoV94** [comment]
@OriolAbril Is this issue still relevant? If so what's needed to close it?

**Comment by OriolAbril** [comment]
It is still relevant. I created this issue for two reasons. 1) to hopefully drive people from here pymc repo to the pymc-examples one. 2) to have it appear on the 4.0 milestone. 

This issue is not about re-executing the notebooks with v4, this can happen after v4 is released as stable, every time a notebook is merge the pymc-examples website is updated. It is about adding all the necessary metadata (aka have all notebooks be at least in best practices column, but better if in book style one).

In v4 docs, notebooks are no longer embedded, they are now in the independent and unversioned pymc-examples website. The pymc-examples website doesn't have a hierarchy either, notebooks are browsed via tags and categories. Therefore, notebooks without tags are only reachable by searching from them on the search bar.

**Comment by twiecki** [comment]
Should be fixed.

**Comment by OriolAbril** [comment]
I haven't tracked progress these last days but I think this has barely advanced as updating to v4 but not updating the style was prioritized. This should only be closed once all notebooks have the right metadata, references, authorship...

**Comment by twiecki** [comment]
Oh I thought this was about the gallery itself, sorry.

**Comment by ricardoV94** [comment]
@OriolAbril can we close this and open an issue with the specific things that are still missing (metadata, etc). As is this issue feels very unactionable.

**Comment by OriolAbril** [comment]
This issue is only to drive people to pymc-examples. There already are specific issues per notebook all of which are classified in the status tracker (linked in the description) according to the changes needed in each notebook. Maybe we can improve the issue description

**Comment by ricardoV94** [comment]
Why not open an issue on "how to help" that we can pin and directs people to examples and experimental? Something like this: https://github.com/blackjax-devs/blackjax/issues/154

I think this issue is too messy to do that well atm.
