### ISSUE TITLE
Rebuild conda packages

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#556]
The conda packages for pymc 2.3 are not compatible with current anaconda versions. We thus need to rebuild and reupload. I can do linux 64bit, @fonnesbeck can you do osx 64bit?

**Comment by fonnesbeck** [comment]
Yes. Will release 2.3.3 today, so hold tight.

**Comment by aflaxman** [comment]
It would be great to have x64 windows version as well. :)

**Comment by twiecki** [comment]
I think 64bit windows has problems with fortran. I can do 32 bit though.

**Comment by aflaxman** [comment]
If you are up for experimenting, I saw some hints on 64bit windows and fortran here: https://twitter.com/ContinuumIO/status/481908466047803392

**Comment by fonnesbeck** [comment]
@twiecki Branch 2.3 contains my fixes and updates for 2.3.3. It passes locally and on Travis, so have a peek and I will tag it if you think it looks okay.

**Comment by twiecki** [comment]
Looks good to me :+1:. Let me know once you updated pypi.

**Comment by fonnesbeck** [comment]
[Done](https://pypi.python.org/pypi?:action=display&name=pymc&version=2.3.3)

**Comment by twiecki** [comment]
RuntimeError: MD5 mismatch: '99645bf558a41376be0e687ccf90a39f' !=
'ea95fd6186a5c08937744f38f85390b9'

On Tue, Jul 1, 2014 at 7:40 PM, Chris Fonnesbeck notifications@github.com
wrote:

> Done
> https://pypi.python.org/pypi?:action=display&name=pymc&version=2.3.3
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc/issues/556#issuecomment-47686933.

## 

Thomas Wiecki
PhD candidate, Brown University
Quantitative Researcher, Quantopian Inc, Boston

**Comment by fonnesbeck** [comment]
PyPI created the MD5 automatically, so not sure what's up.

**Comment by twiecki** [comment]
linux 64 updated https://binstar.org/pymc/pymc/2.3.3/files

On Tue, Jul 1, 2014 at 7:49 PM, Chris Fonnesbeck notifications@github.com
wrote:

> PyPI created the MD5 automatically, so not sure what's up.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc/issues/556#issuecomment-47688059.

## 

Thomas Wiecki
PhD candidate, Brown University
Quantitative Researcher, Quantopian Inc, Boston

**Comment by terhardt** [comment]
I have the same problem with the md5 checksum. The last time something was wrong with one of the various caches that conda uses, didn't fix it this time.

Maybe the problem is, that the md5 changes as soon as we put the md5 in the build recipe. In that way they will never match up.

I've pushed a good build to binstar:
https://binstar.org/pymc/pymc/2.3.3/download/osx-64/pymc-2.3.3-np18py27_0.tar.bz2

**Comment by twiecki** [comment]
@tobeplugged Yeah, I also just manually changed the md5 string. Should probably just replace that. I don't think we need to update the pypi version for that.

Since you're set up to do this and have pymc installed successfully, would you be willing to help me upload a hddm conda for osx? Build files etc are all in place and it works well for linux so should just be a conda build and binstar upload. Of course no worries if not.

**Comment by terhardt** [comment]
I've just build 3.3 and 3.4 packages for OSX as well:

https://binstar.org/pymc/pymc/2.3.3/download/osx-64/pymc-2.3.3-np18py33_0.tar.bz2
https://binstar.org/pymc/pymc/2.3.3/download/osx-64/pymc-2.3.3-np18py34_0.tar.bz2

Sure building hddm should be no problem. But I cannot find the recipe in the repository, or am I missing something?

**Comment by twiecki** [comment]
I just uploaded windows 32 bit for py2.

Building hddm should be the same, just checkout master, and then from the root `conda build conda` should do the trick.

**Comment by terhardt** [comment]
I wasn't looking in the right repo...

voila:

> Removed download link

build like a charm. I did not check, but if the package does not have any compiled code, than it should be possible to build cross platform as well.

I'll remove the file as soon as its up on binstar.

**Comment by twiecki** [comment]
Actually, you could just upload it to the pymc repo as well. It has cython
so probably not cross-platform.

On Wed, Jul 2, 2014 at 1:48 PM, Tobias notifications@github.com wrote:

> I wasn't looking in the right repo...
> 
> voila:
> https://www.dropbox.com/s/pwq5ibvakpedqm8/hddm-0.5.4-np18py27_0.tar.bz2
> build like a charm. I did not check, but if the package does not have any
> compiled code, than it should be possible to build cross platform as well.
> 
> I'll remove the file as soon as its up on binstar.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc/issues/556#issuecomment-47766291.

## 

Thomas Wiecki
PhD candidate, Brown University
Quantitative Researcher, Quantopian Inc, Boston

**Comment by terhardt** [comment]
Okay, I'll do that. I thought you might want to keep the channels apart and make a new channel for hddm

**Comment by twiecki** [comment]
I had that for a while but the installation is easier that way. I don't think it could cause any problems.

**Comment by terhardt** [comment]
Turns out that I cannot upload to pymc I always get an error that the file was not found. Maybe I do not have the permissions.

See here:
https://github.com/Binstar/binstar_client/issues/63

Edit:
for hddm that is.

I've build and uploaded 3.3 and 3.4 versions of pymc for 64 bit Linux as well.

**Comment by twiecki** [comment]
OK, I uploaded the dropbox file. Unfortunately it also needs kabuki which
is a source package. Could I bother you to also create an osx upload for
hddm-devs/kabuki?

On Wed, Jul 2, 2014 at 2:04 PM, Tobias notifications@github.com wrote:

> Turns out that I cannot upload to pymc I always get an error that the file
> was not found. Maybe I do not have the permissions.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc/issues/556#issuecomment-47767507.

## 

Thomas Wiecki
PhD candidate, Brown University
Quantitative Researcher, Quantopian Inc, Boston

**Comment by terhardt** [comment]
No problem:
you can find it here:

> removed download link

I did not build against Python 3 because kabuki did not seem to be compatible.

I have a script that builds a package against all possible combinations of Python (and numpy) so doing the builds for the Pythons is not a big deal.

**Comment by twiecki** [comment]
Many thanks, I really appreciate it.

A user just tried to install but gets a pymc-related error (on osx):

```
ImportError: dlopen(//anaconda/lib/python2.7/site-packages/pymc/flib.so, 2): Library not loaded: /usr/local/Cellar/gfortran/4.8.2/gfortran/lib/libgfortran.3.dylib

  Referenced from: //anaconda/lib/python2.7/site-packages/pymc/flib.so

  Reason: image not found
```

Any ideas? Is a separate fortran library required even with anaconda?

**Comment by terhardt** [comment]
Okay, that is weird. I can load and run pymc with no problem on my machine after installing from binstar.

**Comment by twiecki** [comment]
Do you have that directory?

On Wed, Jul 2, 2014 at 3:03 PM, Tobias notifications@github.com wrote:

> Okay, that is weird. I can load and run pymc with no problem on my machine
> after installing from binstar.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc/issues/556#issuecomment-47772561.

## 

Thomas Wiecki
PhD candidate, Brown University
Quantitative Researcher, Quantopian Inc, Boston

**Comment by terhardt** [comment]
Yes I do have that directory. But the even with a fresh environment, I have no problems running PyMC.

And the `flib.so` file is part of the binary packages that I've uploaded.

**Comment by twiecki** [comment]
Right, but it seems to be linked against the other lib dynamically which
doesn't exist on the other system. Do you know where Cellar might be coming
from?

On Wed, Jul 2, 2014 at 3:10 PM, Tobias notifications@github.com wrote:

> Yes I do have that directory. But the even with a fresh environment, I
> have no problems running PyMC.
> 
> And the flib.so file is part of the binary packages that I've uploaded.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc/issues/556#issuecomment-47773306.

## 

Thomas Wiecki
PhD candidate, Brown University
Quantitative Researcher, Quantopian Inc, Boston

**Comment by terhardt** [comment]
That is from homebrew. The library it is linked against is gfortran which I use to build it in the first place.

**Comment by twiecki** [comment]
I see. We might want to statically link in that case or provide the library with pymc together.

**Comment by terhardt** [comment]
That would be good. Shouldn't that just be another flag in the `conda/build.sh` script?

**Comment by twiecki** [comment]
You can try `-static` to the linker.

**Comment by twiecki** [comment]
Although I expect that anaconda should come with it's own libgfortran. Maybe it's just a matter of making it link against this one.

**Comment by terhardt** [comment]
It does not seem to come with any. However I could make it link statically against my `libgfortran` but it also links against `libquadmath` which I did not find a way to link statically against.

I've uploaded a new build on my binstar account. Can you test it?

**Comment by twiecki** [comment]
Didn't seem to make a difference (assuming it got reinstalled correctly).

**Comment by terhardt** [comment]
Okay, just to make sure that it is installed correctly please try again. I've build it with a higher build number so that it should prefer the most current one.

**Comment by terhardt** [comment]
You should be able to install it via

`conda install -c https://conda.binstar.org/tobeplugged pymc`

into a fresh conda environment.

Looking through the mailing list, I've come across some mentions about libgfortran. It seems, that it was included in anaconda but it is not anymore. But I think the Linux builds also link against the system libgfortran, don't they?

**Comment by twiecki** [comment]
Oh, do you not have upload access to the pymc channel?

**Comment by twiecki** [comment]
There seem to be additional problems:

```
----> 2 import pymc as pm
      3 import numpy as np
      4 from scipy import stats
      5 

/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/__init__.pyc in <module>()
     28 from .PyMCObjects import *
     29 from .InstantiationDecorators import *
---> 30 from .CommonDeterministics import *
     31 from .NumpyDeterministics import *
     32 from .distributions import *

/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/CommonDeterministics.py in <module>()
     11 __docformat__ = 'reStructuredText'
     12 
---> 13 from . import PyMCObjects as pm
     14 from .Node import Variable
     15 from .Container import Container

ImportError: cannot import name PyMCObjects
```

**Comment by fonnesbeck** [comment]
Yes, I saw this on a [SO post](http://stackoverflow.com/questions/24537795/cannot-import-name-pymcobjects-when-import-pymc) earlier today.

**Comment by twiecki** [comment]
@fonnesbeck did you upload the conda packages to the pymc channel?

**Comment by fonnesbeck** [comment]
Nope, I thought you did!--
Christopher Fonnesbeck
Assistant Professor of Biostatistics
Department of Biostatistics
Vanderbilt Center for Quantitative Sciences
Vanderbilt University School of Medicine

**Comment by terhardt** [comment]
@twiecki Yes, I do have the permissions. I just didn't want to clutter the feed with test builds.

I'm not sure what the issue here is. But, if I'd have to point at something it would be gfortran. 
The version I used to build the packages is the one that comes with `brew install gcc`, which is 4.8.2.
However for OSX 10.9 there is a news version (4.9 as well). 
We should probably use the one that is used to compile the numpy binaries on anaconda.

The other problem seems to be that the current build process does not produce statically linked libraries.

**Comment by twiecki** [comment]
Maybe we can get one of the Continuum guys here to help us, they must have dealt with fortran issues. Ping @asmeurer @ilanschnell

**Comment by terhardt** [comment]
Yeah, that might be a good idea.

I've just tried to run the build from binstar with both none and an 
other gfortran installation and got the same error that you described 
above. There is definitely something wrong with those builds...

**Comment by terhardt** [comment]
For what It is worth, I've pushed a branch with the current version of the build recipe:

https://github.com/tobeplugged/pymc/tree/conda

This is still experimental except the change to the MANIFEST.in to exclude the conda recipe from the pypi package.

**Comment by asmeurer** [comment]
We actually build against an old version of OS X, for backwards compatibility reasons. I'm not sure if it's 10.5 or if we've moved to 10.7 (we do plan to move to 10.7).

**Comment by ilanschnell** [comment]
Most packages are now build against OSX 10.7, although there are still some which have been build against 10.5.  However, we are moving to build all packages against 10.7, and do not support 10.5 (or 10.6) any longer.

**Comment by asmeurer** [comment]
Which compiler is used?

**Comment by ilanschnell** [comment]
several have been used, gcc 4.0.1, gcc 4.2.1 (on OSX 10.5) and clang 4.0 (on 10.7)

**Comment by twiecki** [comment]
@ilanschnell @asmeurer thanks for chiming in. I also talked to Andy to get PyMC into the anaconda main repo. What are the chances of that happening anytime soon?

**Comment by fonnesbeck** [comment]
We had a handful of folks at the SciPy tutorial who were having this issue. Seemed to be happening with 2.7 and 3.4.

**Comment by ilanschnell** [comment]
pymc 2.3.3 is available in the Anaconda repo on Linux (for Python 2.6 and
2.7).  The last time I tried, I has still problems compiling it on Mac OS
X, however.

**Comment by terhardt** [comment]
@fonnesbeck that is annoying. Sorry to hear that.

I do not have access to an older OSX Version. But I'll try to set up a 
Virtual Machine with OSX 10.7 to try and build the packages the way 
continuum does. I'll probably only get around to do that on the weekend 
though.

**Comment by twiecki** [comment]
@ilanschnell @asmeurer Are OSX and windows builds in the works or do we have to provide them? I fear that if you can't get them to compile our efforts would be futile.

**Comment by asmeurer** [comment]
Is the recipe on conda-recipes the one you want? Does the build I just made for OS X work?

**Comment by twiecki** [comment]
No, we have our own here: https://github.com/pymc-devs/pymc/tree/2.3/conda

**Comment by twiecki** [comment]
Yours should be available by just doing `conda install pymc`?

**Comment by asmeurer** [comment]
Sorry, I mean the build on my binstar channel.

**Comment by twiecki** [comment]
I asked the users who had problems to try.

**Comment by asmeurer** [comment]
I just built your recipe (as build number 1) and also have it on my binstar channel (for OS X). It compiled fine.

**Comment by asmeurer** [comment]
It doesn't support Python 3 right? I got an error when building there, which looked like an implicit relative import.

**Comment by twiecki** [comment]
Yeah, compiling was not the problem but the packages failed to run on the user end.

Where was the implicit import? We try to maintain it but often break it.

**Comment by asmeurer** [comment]
It couldn't import distances. But it looks like the recipe from this repo builds.

**Comment by twiecki** [comment]
This is the user error description:

```
here is the error I get for pymc. I believe it is more or less the same as before.
Looks like it's looking for "Cellar" from homebrew. Is that gfortran library something I need to install with that path? I would have though that would come via Anaconda.

In [3]: import pymc as mc
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-b5e4a67f5f71> in <module>()
----> 1 import pymc as mc

/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/__init__.pyc in <module>()
     28 from .PyMCObjects import *
     29 from .InstantiationDecorators import *
---> 30 from .CommonDeterministics import *
     31 from .NumpyDeterministics import *
     32 from .distributions import *

/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/CommonDeterministics.py in <module>()
     19 import inspect
     20 import types
---> 21 from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
     22 from copy import copy
     23 import sys

/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/utils.py in <module>()
     12 from copy import copy
     13 from .PyMCObjects import Variable
---> 14 from . import flib
     15 import pdb
     16 from numpy.linalg.linalg import LinAlgError

ImportError: dlopen(/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/flib.so, 2): Library not loaded: /usr/local/Cellar/gfortran/4.8.2/gfortran/lib/libgfortran.3.dylib
  Referenced from: /Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/flib.so
  Reason: image not found
```

**Comment by asmeurer** [comment]
I see. So we need to build a conda package for libgfortran.

**Comment by rafaelkaufmann** [comment]
:+1: , I get the same error as @twiecki reports above. Would greatly appreciate any updates on this. :)

**Comment by cdagnino** [comment]
Hi, I'm having the exact same Traceback too. Is the recommended conda installation to use `conda install -c https://conda.binstar.org/pymc pymc` ? I get the the same `homebrew` conflict. When I try to do `pip install pymc` it throws a different error though. I tried different `gfortran` compilers and none worked for `pip`, though each one threw a different error. Just in case it's of any help, [here's my Stackoverflow](http://stackoverflow.com/questions/24853812/failure-to-import-pymc-gfortran-library-not-loaded-after-installing-from-conda) question with more details.

**Comment by terhardt** [comment]
@rafaelkaufmann @cdagnino At the moment we cannot build any conda installable packages for OSX at all. The build itself does work, but no one is able to install the packages on a different machine than the one it was build against. 

One possible (not tested) workaround is to install `gcc` from homebrew, which includes the compiler which the packages are build against. But be aware, that might break other things on your machine.

@asmeurer that might do the trick

**Comment by terhardt** [comment]
Sorry, I should have read the SO thread. That workaround of course only works for the correct version of gfortran... What a mess.

**Comment by terhardt** [comment]
Hey, I've spend some time messing around with the compiler that is to be used to build the package.
I've managed to build a packaged that seems to work without having any gfortran installed.

Is anyone willing to give it a try to confirm that?
`conda install -c https://conda.binstar.org/tobeplugged pymc`
should get the right build (`pymc-2.3.3-np18py27_2`). 

As soon as it is confirmed, that this works I'll rebuild all the packages and update the conda recipe accordingly.

**Comment by rafaelkaufmann** [comment]
Hi @tobeplugged, running `conda install -c https://conda.binstar.org/tobeplugged pymc` does claim to unlink `pymc-2.3.3-np18py27_1` and link `pymc-2.3.3-np18py27_2`. However, attempting to `import pymc` gives me the exact same error still. Is there some intermediate step I might be missing?

(Note: I do have a gfortran installed, the latest version for OSX, and tried to compile pymc from source, which of course handed off a bunch of warnings and failed with a `ld: library not found for -lbundle1.o`...)

**Comment by fonnesbeck** [comment]
Happily, PyMC 3 will have no Fortran extensions. Tempted to eliminate them for PyMC 2 as well.

**Comment by twiecki** [comment]
One quite easy path would be to replace the fortran code with the probability distributions from GSL (CythonGSL already provides an interface). Of course, would need to redistribute under GPL.

**Comment by fonnesbeck** [comment]
Actually, I was thinking of Cython but not GSL. Might make for a good student project.

**Comment by twiecki** [comment]
Perhaps we could also reuse the Theano likelihoods from pymc 3.

**Comment by cdagnino** [comment]
Hi @tobeplugged, I tried `conda install -c https://conda.binstar.org/tobeplugged pymc` and it installed OK in my computer.
I imported pymc and it passed the tests!

Below is the info for the gfortran compiler I have installed now, installed with `brew install gcc`.
I'd try installing it without that gfortran compiler, but I'm afraid of breaking other things.

```gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/4.8.3_1/libexec/gcc/x86_64-apple-darwin13.2.0/4.8.3/lto-wrapper
Target: x86_64-apple-darwin13.2.0
Configured with: ../configure --build=x86_64-apple-darwin13.2.0 --prefix=/usr/local/Cellar/gcc/4.8.3_1 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.8 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-cloog=/usr/local/opt/cloog --with-isl=/usr/local/opt/isl --with-system-zlib --enable-version-specific-runtime-libs --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion='Homebrew gcc 4.8.3_1' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --enable-multilib
Thread model: posix
gcc version 4.8.3 (Homebrew gcc 4.8.3_1)

```
```

**Comment by asmeurer** [comment]
http://stackoverflow.com/q/24853812/161801

**Comment by asmeurer** [comment]
As a work-around, you can try copying the gfortran libraries that pymc was built with into the conda package. Conda's post-processing install_name_tool should hopefully change the RPATH to point to it correctly.

**Comment by clithero** [comment]
@tobeplugged I am using Anaconda 2.0.1 on OSX 10.8.4. I just tried the new build `conda install -c https://conda.binstar.org/tobeplugged pymc` without having first done  `brew install gcc`. 

Looked ok but I get this:
```In [1]: import pymc as mc
Couldn't import dot_parser, loading of dot files will not be possible.
In [2]: mc.test('full')
Running unit tests for pymc.tests
NumPy version 1.8.1
NumPy is installed in /Users/jac54747/anaconda/lib/python2.7/site-packages/numpy
Python version 2.7.8 |Anaconda 2.0.1 (x86_64)| (default, Jul  2 2014, 15:36:00) [GCC 4.2.1 (Apple Inc. build 5577)]
nose version 1.3.3
.....Could not generate output statistics for early_mean
.E..F............E.............S.......................................................................................................0            x
1    (x_pow_2)
dtype: object

#  [-----------------100%-----------------] 1000 of 1000 complete in 0.4 sec............

## ERROR: test_stats_after_reload (pymc.tests.test_MCMCSampler.test_MCMC)

Traceback (most recent call last):
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/tests/test_MCMCSampler.py", line 78, in test_stats_after_reload
    db = database.pickle.load('MCMC.pickle')
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/database/pickle.py", line 82, in load
    file = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: 'MCMC.pickle'

# 

## ERROR: test suite for <class 'pymc.tests.test_database.TestHDF5'>

Traceback (most recent call last):
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/nose/util.py", line 470, in try_run
    return func()
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/tests/test_database.py", line 311, in setUpClass
    dbmode='w')
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/MCMC.py", line 82, in **init**
    **kwds)
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/Model.py", line 207, in **init**
    self._assign_database_backend(db)
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/Model.py", line 574, in _assign_database_backend
    self.db = module.Database(**self._db_args)
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/database/hdf5.py", line 276, in __init__
    self._h5file = tables.openFile(self.dbname, self.mode)
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/tables/_past.py", line 35, in oldfunc
    return obj(_args, *_kwargs)
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/tables/file.py", line 315, in open_file
    "close it before reopening in write mode." % filename)
ValueError: The file 'testresults/Disaster.hdf5' is already opened.  Please close it before reopening in write mode.

# 

## FAIL: test_nonsep (pymc.tests.test_basiscov.test_basiscov)

Traceback (most recent call last):
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/tests/test_basiscov.py", line 82, in test_nonsep
    assert_almost_equal(C2(xstack), C(xstack))
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 454, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 811, in assert_array_almost_equal
    header=('Arrays are not almost equal to %d decimals' % decimal))
  File "/Users/jac54747/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 100.0%)
 x: array([[ 21.75818765,  21.75818765,  21.75818765, ...,  21.75818765,
         21.75818765,  21.75818765],
       [ 21.75818765,  21.75818765,  21.75818765, ...,  21.75818765,...
 y: array([[ 21.36447983,  21.49335719,  21.58260819, ...,  21.58260819,
         21.49335719,  21.36447983],
       [ 21.45954895,  21.58904931,  21.68019077, ...,  21.68019077,...

---

Ran 178 tests in 59.742s

FAILED (SKIP=1, errors=2, failures=1)
Out[3]: <nose.result.TextTestResult run=178 errors=2 failures=1>```

**Comment by fonnesbeck** [comment]
@clithero Make sure to use proper Markdown syntax when pasting code or output (indent 4 spaces).

**Comment by rafaelkaufmann** [comment]
@twiecki @fonnesbeck, any progress? Anything I can do to help? Really no experience with developing Python libraries, but I can follow instructions :)

**Comment by twiecki** [comment]
Not from my end. @asmeurer are you working on this or is the ball in our park?

**Comment by asmeurer** [comment]
OK, so I've managed to build gcc 4.8 for OS X (built on Mac OS X 10.7). See the conda-recipes repo and my binstar channel. I built a version of pymc that build and runtime depends on gcc. 

This is obviously not ideal. We should make a package that is just libgfortran for installing, but let's see if this works first. Can you guys see if `conda install -c asmeurer pymc` works (I have only built for 2.7 so far, it should be build py27_1).

**Comment by asmeurer** [comment]
Oh, and one other thing. The only way I was able to build gcc was with `--without-multilib`. Hopefully that won't lead to any problems.

**Comment by clithero** [comment]
Apologies if this is not posted correctly. I did the install as you suggest on OS X 10.8 `conda install -c asmeurer pymc` after running `conda install -c https://conda.binstar.org/asmeurer gcc` which seemed to work fine (also tried without and got the same error)

I get this when trying to import pymc. I probably missed something?

`````` ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b5e4a67f5f71> in <module>()
----> 1 import pymc as mc

/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/__init__.pyc in <module>()
     28 from .PyMCObjects import *
     29 from .InstantiationDecorators import *
---> 30 from .CommonDeterministics import *
     31 from .NumpyDeterministics import *
     32 from .distributions import *

/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/CommonDeterministics.py in <module>()
     19 import inspect
     20 import types
---> 21 from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
     22 from copy import copy
     23 import sys

/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/utils.py in <module>()
     12 from copy import copy
     13 from .PyMCObjects import Variable
---> 14 from . import flib
     15 import pdb
     16 from numpy.linalg.linalg import LinAlgError

ImportError: dlopen(/Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/flib.so, 2): Library not loaded: /usr/local/lib/gcc/x86_64-apple-darwin11.4.2/4.8.3/libgfortran.3.dylib
  Referenced from: /Users/jac54747/anaconda/lib/python2.7/site-packages/pymc/flib.so
  Reason: image not found````
``````

**Comment by asmeurer** [comment]
Hmm. Yeah, it definitely didn't actually build my gcc package. Need to figure out why.

**Comment by asmeurer** [comment]
Ah, the problem is that I built against the older pymc recipe, so the version I built was not the latest.

**Comment by asmeurer** [comment]
OK, try again. `conda install -c asmeurer pymc`. It should install gcc along with it. If it doesn't, it's doing the wrong thing.

**Comment by clithero** [comment]
Not sure if it installed gcc. Just tried `conda install -c asmeurer` and got the same error as before. Here is what it looked like after running the above command:

``````
$ conda install -c asmeurer pymc
Fetching package metadata: ...
Solving package specifications: ...............
Package plan for installation in environment /Users/jac54747/anaconda:

The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    pymc-2.3.3                 |       np18py27_1   hard-link

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ] |#####################################################################################################| 100%````
``````

**Comment by asmeurer** [comment]
Ah, crap, it turns out I built only for 3.4, not 2.7. Try again (third time's a charm). It should install build np18py27_3.

**Comment by clithero** [comment]
Progress! It looked for build np18py27_2, not 3. Otherwise it did not kick out errors on import, but it did say this?

```
In [1]: import pymc as mc
Couldn't import dot_parser, loading of dot files will not be possible.
```

**Comment by asmeurer** [comment]
Oh yeah sorry, that should be 2. It was the 3rd build. 0-indexing...

**Comment by asmeurer** [comment]
One of the pymc devs will have to comment on what that dot_parser thing means.

**Comment by cdagnino** [comment]
dot_parser is part of pydot, for building directed acyclical graphs with GraphViz. A PyMC dev can correct me, but pydot is listed as optional in [http://pymc-devs.github.io/pymc/INSTALL.html](http://pymc-devs.github.io/pymc/INSTALL.html)

**Comment by asmeurer** [comment]
OK. That wasn't in the requirements in the recipe I used. I can add it if it causes an error to be printed.

**Comment by rafaelkaufmann** [comment]
Before I try to install this, a newbie question: where will the "new" gcc get installed? Is there a chance it will conflict with the Apple-provided gcc that's part of Developer Tools (and eventually break my projects on Xcode)? :S

**Comment by ilanschnell** [comment]
The "new" (conda) gcc will be installed into a conda environment, e.g. `$HOME/anaconda`, just like any other conda package, and will therefore not conflict with the Xcode gcc.

**Comment by asmeurer** [comment]
It will be put on your PATH by default, though, so that `gcc` will end up calling this gcc. If you are worried about it, you can create a separate conda environment for it

```
conda create -n pymc-test pymc -c asmeurer
```

And then use

```
source activate pymc-test
```

to test it. This is a good idea anyway, as the package I built may not be stable yet.

**Comment by fonnesbeck** [comment]
To clarify, the pydot dependency is completely optional. Its used to generate a plot of the directed acyclic graph, which is not required to run models.

**Comment by twiecki** [comment]
@asmeurer Seems like the current package (release 2) works well. What did you change?

However, when then trying to install hddm from the pymc channel it tries to pull in pymc 2.3.3 (release 0) from that same channel. Shouldn't conda prefer newer releases?

**Comment by asmeurer** [comment]
I built and linked against my own gcc. Right now, the entire gcc package is a dependency of my pymc. It would be better to extract just the libraries.

Conda does prefer newer versions. Did you add my channel permanently to your configuration with `conda config --add channels`. The `-c` flag only adds the channel once for that command.

**Comment by twiecki** [comment]
@asmeurer OK, your package seems to work fine for my OSX user. Can you do a PR with the changes to your recipe?

**Comment by asmeurer** [comment]
I think before we include this in your recipe, we should figure out how to extract the fortran libraries from my gcc package, so that you don't have to depend on it at run time (ideally, you wouldn't depend on it at build time either, although you obviously have to have _a_ fortran compiler). My gcc package is 68 MB archived and 250 MB unarchived, so runtime depending on it is non-ideal. We also don't have it in the official Continuum repos, only my binstar channel, although that is easy enough to fix.

**Comment by asmeurer** [comment]
Is it enough to just extract the dylibs it links against? According to otool, they are libgcc_s.1.dylib, libgfortran.3.dylib, and libquadmath.0.dylib.

**Comment by asmeurer** [comment]
The recipes for pymc and gcc that I used are at https://github.com/conda/conda-recipes/tree/master/pymc BTW.

**Comment by twiecki** [comment]
You know more about this than I but I would assume so.

**Comment by rafaelkaufmann** [comment]
Hi guys, both when trying to create an environment and when trying to `conda install`, I get:

`Error: No packages found matching: gmp >=4.2`

This is weird, since it's pulling from @asmeurer's channel, right?

**Comment by asmeurer** [comment]
Yeah, as long as you are using `-c asmeurer` or have added my channel to your .condarc, it should pick that up. You are on OS X, right?

**Comment by twiecki** [comment]
@asmeurer Is there any update in anaconda that would be relevant to this? Just starting to look back into it. Otherwise we could probably just use your conda script and ship with gfortran?

**Comment by asmeurer** [comment]
I haven't done anything with this. We (or you) would need to ship a gfortran library that this could link against.

**Comment by twiecki** [comment]
I suppose we could just statically compile against gfortran.

**Comment by asmeurer** [comment]
If it's possible for you to not depend on libgfortran that would be a much better option, I'd say.

**Comment by twiecki** [comment]
That's impossible unfortunately.

**Comment by asmeurer** [comment]
I meant including static linking.

**Comment by twiecki** [comment]
Turns out there's a handy flag for this `-static-libgfortran`. Unfortunately, it causes:

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/libgfortran.a(compile_options.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.8/libgfortran.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/libgfortran.a(compile_options.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.8/libgfortran.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```

While compiling... (I do use `-fPIC` during compile).

**Comment by twiecki** [comment]
Ugh, turns out `gfortran` needs to be compiled with `-fPIC` which it wasn't on ubuntu...

**Comment by twiecki** [comment]
Well, actually linux is not the problem. As long as we get the binary installation on OSX and Windows we should be fine. Can anyone on OSX try this: I changed setup.py to this:

``` python
if lapack_info:
    config.add_extension(name='flib', sources=f_sources,
                         extra_info=lapack_info, f2py_options=['skip:ppnd7'],,
                         extra_link_args=['-static-libgfortran'])
```

If this compiles fine on OSX or Windows we might be in business.

**Comment by asmeurer** [comment]
Can you paste a full patch for setup.py?

**Comment by twiecki** [comment]
``` diff
diff --git a/setup.py b/setup.py
index f2acc07..25a8cf6 100755
--- a/setup.py
+++ b/setup.py
@@ -23,8 +23,9 @@ lapack_info = get_info('lapack_opt',1)
 f_sources = ['pymc/flib.f','pymc/histogram.f', 'pymc/flib_blas.f', 'pymc/blas_wrap.f', 'pymc/math.f', 'pymc/gibbsit.f', 
              'cephes/c2f.c','cephes/chbevl.c']
 if lapack_info:
-    config.add_extension(name='flib',sources=f_sources, extra_info=lapack_info, f2py_options=['skip:ppnd7'])
-
+    config.add_extension(name='flib', sources=f_sources,
+                         extra_info=lapack_info, f2py_options=['skip:ppnd7'],
+                         extra_link_args=['-static-libgfortran'])
 if not lapack_info or dist in ['bdist', 'sdist']:
     ##inc_dirs = ['blas/BLAS','lapack/double']
     print('No optimized BLAS or Lapack libraries found, building from source. This may take a while...')
@@ -122,4 +123,3 @@ if __name__ == '__main__':
             """,
             packages=["pymc", "pymc/database", "pymc/examples", "pymc/examples/gp", "pymc/tests", "pymc/gp", "pymc/gp/co
             **(config_dict))
-
```

**Comment by asmeurer** [comment]
OK, I'll try applying that patch in the conda recipe and see if it builds (and works without gcc as a runtime dependency).

**Comment by asmeurer** [comment]
On OS X that is.

**Comment by twiecki** [comment]
Great, that's very helpful.

**Comment by asmeurer** [comment]
Why does your diff have the `@@ -122,4 +125,3 @@ if __name__ == '__main__':` part at the end? Did you miss part of the output? The patch didn't work unless I removed it, assumedly because there are no changes there.

**Comment by asmeurer** [comment]
It failed:

``` pytb
===== testing package: pymc-2.3.3-np19py34_3 =====
import: 'pymc'
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import pymc
  File "/Users/aaronmeurer/anaconda/envs/_test/lib/python3.4/site-packages/pymc/__init__.py", line 30, in <module>
    from .CommonDeterministics import *
  File "/Users/aaronmeurer/anaconda/envs/_test/lib/python3.4/site-packages/pymc/CommonDeterministics.py", line 21, in <module>
    from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
  File "/Users/aaronmeurer/anaconda/envs/_test/lib/python3.4/site-packages/pymc/utils.py", line 14, in <module>
    from . import flib
ImportError: dlopen(/Users/aaronmeurer/anaconda/envs/_test/lib/python3.4/site-packages/pymc/flib.so, 2): Symbol not found: ___addtf3
  Referenced from: /Users/aaronmeurer/anaconda/envs/_test/lib/python3.4/site-packages/pymc/flib.so
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by twiecki** [comment]
Yes, I messed up the diff. I updated it now.

Bummer it doesn't work. Can you try again with this diff:

``` diff
diff --git a/setup.py b/setup.py
index f2acc07..1dc835e 100755
--- a/setup.py
+++ b/setup.py
@@ -23,7 +23,10 @@ lapack_info = get_info('lapack_opt',1)
 f_sources = ['pymc/flib.f','pymc/histogram.f', 'pymc/flib_blas.f', 'pymc/blas_wrap.f', 'pymc/math.f', 'pymc/gibbsit.f', 
              'cephes/c2f.c','cephes/chbevl.c']
 if lapack_info:
-    config.add_extension(name='flib',sources=f_sources, extra_info=lapack_info, f2py_options=['skip:ppnd7'])
+    config.add_extension(name='flib', sources=f_sources,
+                         extra_info=lapack_info, f2py_options=['skip:ppnd7'],
+                         extra_compile_args=['-fPIC'],
+                         extra_link_args=['-static-libgfortran'])

 if not lapack_info or dist in ['bdist', 'sdist']:
     ##inc_dirs = ['blas/BLAS','lapack/double']
@@ -122,4 +125,3 @@ if __name__ == '__main__':
             """,
             packages=["pymc", "pymc/database", "pymc/examples", "pymc/examples/gp", "pymc/tests", "pymc/gp", "pymc/gp/co
             **(config_dict))
-
```

**Comment by asmeurer** [comment]
Nope. Same traceback with that patch.

**Comment by asmeurer** [comment]
```
$ otool -L /Users/aaronmeurer/anaconda/envs/_test/lib/python3.4/site-packages/pymc/flib.so
/Users/aaronmeurer/anaconda/envs/_test/lib/python3.4/site-packages/pymc/flib.so:
    /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
    /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1094.0.0)
    @loader_path/../../../libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    @loader_path/../../../libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)

```

**Comment by twiecki** [comment]
Damn. Do you know what's wrong here?

**Comment by asmeurer** [comment]
That's without gcc installed. If I install gcc into that environment it works.

**Comment by twiecki** [comment]
Maybe if we add `-static-libgcc` as well. Do you want a new diff?

**Comment by asmeurer** [comment]
I think the issue is that it's linking against `libgcc_s.1.dylib`. It also finds the one from the system but it's probably too old (this is on OS X 10.7 with gcc 4.2, I compiled with my gcc 4.8 package).

**Comment by twiecki** [comment]
``` diff
diff --git a/setup.py b/setup.py
index f2acc07..e7fdc6c 100755
--- a/setup.py
+++ b/setup.py
@@ -23,7 +23,10 @@ lapack_info = get_info('lapack_opt',1)
 f_sources = ['pymc/flib.f','pymc/histogram.f', 'pymc/flib_blas.f', 'pymc/blas_wrap.f', 'pymc/math.f', 'pymc/gibbsit.f', 
              'cephes/c2f.c','cephes/chbevl.c']
 if lapack_info:
-    config.add_extension(name='flib',sources=f_sources, extra_info=lapack_info, f2py_options=['skip:ppnd7'])
+    config.add_extension(name='flib', sources=f_sources,
+                         extra_info=lapack_info, f2py_options=['skip:ppnd7'],
+                         extra_compile_args=['-fPIC'],
+                         extra_link_args=['-static-libgfortran', '-static-gcc'])

 if not lapack_info or dist in ['bdist', 'sdist']:
     ##inc_dirs = ['blas/BLAS','lapack/double']
@@ -122,4 +125,3 @@ if __name__ == '__main__':
             """,
             packages=["pymc", "pymc/database", "pymc/examples", "pymc/examples/gp", "pymc/tests", "pymc/gp", "pymc/gp/co
             **(config_dict))
-
```

**Comment by asmeurer** [comment]
This?

``` patch
--- setup.py
+++ setup.py
@@ -23,4 +23,7 @@ lapack_info = get_info('lapack_opt',1)
 f_sources = ['pymc/flib.f','pymc/histogram.f', 'pymc/flib_blas.f', 'pymc/blas_wrap.f', 'pymc/math.f', 'pymc/gibbsit.f',
              'cephes/c2f.c','cephes/chbevl.c']
 if lapack_info:
-    config.add_extension(name='flib',sources=f_sources, extra_info=lapack_info, f2py_options=['skip:ppnd7'])
+    config.add_extension(name='flib', sources=f_sources,
+                         extra_info=lapack_info, f2py_options=['skip:ppnd7'],
+                         extra_compile_args=['-fPIC'],
+                         extra_link_args=['-static-libgfortran', '-static-libgcc'])

 if not lapack_info or dist in ['bdist', 'sdist']:
     ##inc_dirs = ['blas/BLAS','lapack/double']
```

**Comment by twiecki** [comment]
Right.

**Comment by asmeurer** [comment]
``` pytb
===== testing package: pymc-2.3.3-np19py34_3 =====
import: 'pymc'
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import pymc
  File "/Users/aaronmeurer/anaconda/envs/_test/lib/python3.4/site-packages/pymc/__init__.py", line 48, in <module>
    from . import gp
  File "/Users/aaronmeurer/anaconda/envs/_test/lib/python3.4/site-packages/pymc/gp/__init__.py", line 20, in <module>
    from .GPutils import *
  File "/Users/aaronmeurer/anaconda/envs/_test/lib/python3.4/site-packages/pymc/gp/GPutils.py", line 14, in <module>
    from .linalg_utils import *
ImportError: dlopen(/Users/aaronmeurer/anaconda/envs/_test/lib/python3.4/site-packages/pymc/gp/linalg_utils.so, 2): Library not loaded: @loader_path/../../../../libgfortran.3.dylib
  Referenced from: /Users/aaronmeurer/anaconda/envs/_test/lib/python3.4/site-packages/pymc/gp/linalg_utils.so
  Reason: image not found
```

**Comment by twiecki** [comment]
This is terrible, I'm out of ideas...

**Comment by twiecki** [comment]
Oh wait, or maybe adding `-static` as well to compile everything statically.

**Comment by asmeurer** [comment]
Now the build fails:

```
pymc/gibbsit.f:2064.5:

   15 IF (KFLAG.GE.1) GO TO 30                                          
     1
Warning: Label 15 at (1) defined but not used
pymc/gibbsit.f:1204.48:

        cutpt = empquant(original,iteracnt,qhat,work)                   
                                                1
Warning: Type mismatch in argument 'work' at (1); passed INTEGER(4) to REAL(8)
gfortran:f77: build/src.macosx-10.5-x86_64-3.4/pymc/flib-f2pywrappers.f
/Users/aaronmeurer/anaconda/envs/_build/bin/gfortran -Wall -g -Wall -undefined dynamic_lookup -bundle -arch x86_64 build/temp.macosx-10.5-x86_64-3.4/cephes/i0.o build/temp.macosx-10.5-x86_64-3.4/cephes/c2f.o build/temp.macosx-10.5-x86_64-3.4/cephes/chbevl.o build/temp.macosx-10.5-x86_64-3.4/build/src.macosx-10.5-x86_64-3.4/pymc/flibmodule.o build/temp.macosx-10.5-x86_64-3.4/build/src.macosx-10.5-x86_64-3.4/fortranobject.o build/temp.macosx-10.5-x86_64-3.4/pymc/flib.o build/temp.macosx-10.5-x86_64-3.4/pymc/histogram.o build/temp.macosx-10.5-x86_64-3.4/pymc/flib_blas.o build/temp.macosx-10.5-x86_64-3.4/pymc/blas_wrap.o build/temp.macosx-10.5-x86_64-3.4/pymc/math.o build/temp.macosx-10.5-x86_64-3.4/pymc/gibbsit.o build/temp.macosx-10.5-x86_64-3.4/build/src.macosx-10.5-x86_64-3.4/pymc/flib-f2pywrappers.o -L/Users/aaronmeurer/anaconda/envs/_build/bin/../lib/gcc/x86_64-apple-darwin11.4.2/4.8.2 -L/Users/aaronmeurer/anaconda/envs/_build/lib -lgfortran -o build/lib.macosx-10.5-x86_64-3.4/pymc/flib.so -static-libgfortran -static-libgcc -static -Wl,-framework -Wl,Accelerate
ld: warning: could not create compact unwind for __Unwind_RaiseException: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_ForcedUnwind: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_Resume: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_Resume_or_Rethrow: does not use RBP or RSP based frame
ld: symbol dyld_stub_binding_helper not found, normally in crt1.o/dylib1.o/bundle1.o for architecture x86_64
collect2: error: ld returned 1 exit status
ld: warning: could not create compact unwind for __Unwind_RaiseException: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_ForcedUnwind: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_Resume: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_Resume_or_Rethrow: does not use RBP or RSP based frame
ld: symbol dyld_stub_binding_helper not found, normally in crt1.o/dylib1.o/bundle1.o for architecture x86_64
collect2: error: ld returned 1 exit status
error: Command "/Users/aaronmeurer/anaconda/envs/_build/bin/gfortran -Wall -g -Wall -undefined dynamic_lookup -bundle -arch x86_64 build/temp.macosx-10.5-x86_64-3.4/cephes/i0.o build/temp.macosx-10.5-x86_64-3.4/cephes/c2f.o build/temp.macosx-10.5-x86_64-3.4/cephes/chbevl.o build/temp.macosx-10.5-x86_64-3.4/build/src.macosx-10.5-x86_64-3.4/pymc/flibmodule.o build/temp.macosx-10.5-x86_64-3.4/build/src.macosx-10.5-x86_64-3.4/fortranobject.o build/temp.macosx-10.5-x86_64-3.4/pymc/flib.o build/temp.macosx-10.5-x86_64-3.4/pymc/histogram.o build/temp.macosx-10.5-x86_64-3.4/pymc/flib_blas.o build/temp.macosx-10.5-x86_64-3.4/pymc/blas_wrap.o build/temp.macosx-10.5-x86_64-3.4/pymc/math.o build/temp.macosx-10.5-x86_64-3.4/pymc/gibbsit.o build/temp.macosx-10.5-x86_64-3.4/build/src.macosx-10.5-x86_64-3.4/pymc/flib-f2pywrappers.o -L/Users/aaronmeurer/anaconda/envs/_build/bin/../lib/gcc/x86_64-apple-darwin11.4.2/4.8.2 -L/Users/aaronmeurer/anaconda/envs/_build/lib -lgfortran -o build/lib.macosx-10.5-x86_64-3.4/pymc/flib.so -static-libgfortran -static-libgcc -static -Wl,-framework -Wl,Accelerate" failed with exit status 1
Command failed: /bin/bash -x -e /Users/aaronmeurer/Documents/conda-recipes/pymc/build.sh
```

**Comment by asmeurer** [comment]
I hope that's enough context. I can paste the whole build log if that helps.

**Comment by twiecki** [comment]
Thanks for trying this. Apparently the static compiling is not the way to go here...

Does anaconda not package gcc?

**Comment by asmeurer** [comment]
No, other than the mingw package on Windows. We could add it (from my build). It wouldn't be part of the installers because it's too big, but we could add it to the repos.

**Comment by twiecki** [comment]
I wonder if this could be related to the outdated gcc you also have installed as you mentioned above. Maybe it's worth for someone else to try this, @fonnesbeck?

**Comment by asmeurer** [comment]
It undoubtedly is, but we want to support older versions of OS X (at least for the Continuum packages we do). 

Actually that makes me wonder if shipping these libs from the newer gcc might break some other package that was built against the older gcc. How good is gcc/gfortran at backwards compatibility?

**Comment by fonnesbeck** [comment]
This fails for me too. I'm using the Homebrew gfortran, so perhaps this is not surprising. 

PyMC is not the only package that relies on Fortran extensions. What is the usual solution?

**Comment by twiecki** [comment]
That's a good question. @asmeurer Doesn't scipy have a bunch of fortran bindings and requires gfortran libraries?

**Comment by asmeurer** [comment]
I think it's statically linked. I'll have to check to be sure. There are packages on Linux that link against gfortran and we just ship a copy of the Linux libgfortran (in the `system` package).

**Comment by twiecki** [comment]
@asmeurer Did you get a chacne to look into how `scipy` makes their fortran code work?

**Comment by asmeurer** [comment]
On OS X, we build scipy with

``` bash
if [ `uname` == Darwin ]; then
    FCFLAGS=$CFLAGS
    # link statically against the fortran libraries
    cp /usr/local/lib/libgfortran*.*a .
    LDFLAGS="-undefined dynamic_lookup -bundle -Wl,-search_paths_first -L$(pwd) $LDFLAGS"
fi

$PYTHON setup.py install
```

**Comment by twiecki** [comment]
Thanks! I don't have OSX so can't try that for `pymc`. Anyone willing to give this a shot? Just change `conda/build.sh`.

**Comment by asmeurer** [comment]
I tried https://github.com/conda/conda-recipes/commit/12d4cad9ed6ca1f3be8c47a61792d6d072487f16 and got

```
gfortran:f77: build/src.macosx-10.5-x86_64-2.6/pymc/flib-f2pywrappers.f
/Users/aaronmeurer/anaconda/envs/_build/bin/gfortran -Wall -g -Wl,-search_paths_first -L/Users/aaronmeurer/anaconda/conda-bld/work/pymc-2.3.3 -Wall -undefined dynamic_lookup -bundle -arch x86_64 build/temp.macosx-10.5-x86_64-2.6/cephes/i0.o build/temp.macosx-10.5-x86_64-2.6/cephes/c2f.o build/temp.macosx-10.5-x86_64-2.6/cephes/chbevl.o build/temp.macosx-10.5-x86_64-2.6/build/src.macosx-10.5-x86_64-2.6/pymc/flibmodule.o build/temp.macosx-10.5-x86_64-2.6/build/src.macosx-10.5-x86_64-2.6/fortranobject.o build/temp.macosx-10.5-x86_64-2.6/pymc/flib.o build/temp.macosx-10.5-x86_64-2.6/pymc/histogram.o build/temp.macosx-10.5-x86_64-2.6/pymc/flib_blas.o build/temp.macosx-10.5-x86_64-2.6/pymc/blas_wrap.o build/temp.macosx-10.5-x86_64-2.6/pymc/math.o build/temp.macosx-10.5-x86_64-2.6/pymc/gibbsit.o build/temp.macosx-10.5-x86_64-2.6/build/src.macosx-10.5-x86_64-2.6/pymc/flib-f2pywrappers.o -L/Users/aaronmeurer/anaconda/envs/_build/bin/../lib/gcc/x86_64-apple-darwin11.4.2/4.8.2 -lgfortran -o build/lib.macosx-10.5-x86_64-2.6/pymc/flib.so -static-libgfortran -static-libgcc -static -Wl,-framework -Wl,Accelerate
ld: warning: could not create compact unwind for __Unwind_RaiseException: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_ForcedUnwind: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_Resume: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_Resume_or_Rethrow: does not use RBP or RSP based frame
ld: symbol dyld_stub_binding_helper not found, normally in crt1.o/dylib1.o/bundle1.o for architecture x86_64
collect2: error: ld returned 1 exit status
ld: warning: could not create compact unwind for __Unwind_RaiseException: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_ForcedUnwind: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_Resume: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_Resume_or_Rethrow: does not use RBP or RSP based frame
ld: symbol dyld_stub_binding_helper not found, normally in crt1.o/dylib1.o/bundle1.o for architecture x86_64
collect2: error: ld returned 1 exit status
error: Command "/Users/aaronmeurer/anaconda/envs/_build/bin/gfortran -Wall -g -Wl,-search_paths_first -L/Users/aaronmeurer/anaconda/conda-bld/work/pymc-2.3.3 -Wall -undefined dynamic_lookup -bundle -arch x86_64 build/temp.macosx-10.5-x86_64-2.6/cephes/i0.o build/temp.macosx-10.5-x86_64-2.6/cephes/c2f.o build/temp.macosx-10.5-x86_64-2.6/cephes/chbevl.o build/temp.macosx-10.5-x86_64-2.6/build/src.macosx-10.5-x86_64-2.6/pymc/flibmodule.o build/temp.macosx-10.5-x86_64-2.6/build/src.macosx-10.5-x86_64-2.6/fortranobject.o build/temp.macosx-10.5-x86_64-2.6/pymc/flib.o build/temp.macosx-10.5-x86_64-2.6/pymc/histogram.o build/temp.macosx-10.5-x86_64-2.6/pymc/flib_blas.o build/temp.macosx-10.5-x86_64-2.6/pymc/blas_wrap.o build/temp.macosx-10.5-x86_64-2.6/pymc/math.o build/temp.macosx-10.5-x86_64-2.6/pymc/gibbsit.o build/temp.macosx-10.5-x86_64-2.6/build/src.macosx-10.5-x86_64-2.6/pymc/flib-f2pywrappers.o -L/Users/aaronmeurer/anaconda/envs/_build/bin/../lib/gcc/x86_64-apple-darwin11.4.2/4.8.2 -lgfortran -o build/lib.macosx-10.5-x86_64-2.6/pymc/flib.so -static-libgfortran -static-libgcc -static -Wl,-framework -Wl,Accelerate" failed with exit status 1
Command failed: /bin/bash -x -e /Users/aaronmeurer/Documents/conda-recipes/pymc/build.sh

```

**Comment by twiecki** [comment]
Did you include the `--static-gfortran` flag we played around with before? Those caused the same issue. Not sure if they're required for the `scipy` linking technique.

**Comment by twiecki** [comment]
Maybe try removing https://github.com/conda/conda-recipes/blob/12d4cad9ed6ca1f3be8c47a61792d6d072487f16/pymc/static_gfortran.patch

**Comment by fonnesbeck** [comment]
Other than my libgfortran being somewhere other than `/usr/local/lib`, the scipy script actually worked for me using miniconda and Python3.4 on OS X 10.10.

**Comment by fonnesbeck** [comment]
I've uploaded my builds to https://binstar.org/fonnesbeck/pymc if anyone wants to try them.

**Comment by asmeurer** [comment]
Oh I forgot that that patch was still there.

**Comment by asmeurer** [comment]
Getting this error again:

```
===== testing package: pymc-2.3.3-np19py26_3 =====
import: 'pymc'
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import pymc
  File "/Users/aaronmeurer/anaconda/envs/_test/lib/python2.6/site-packages/pymc/__init__.py", line 30, in <module>
    from .CommonDeterministics import *
  File "/Users/aaronmeurer/anaconda/envs/_test/lib/python2.6/site-packages/pymc/CommonDeterministics.py", line 21, in <module>
    from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
  File "/Users/aaronmeurer/anaconda/envs/_test/lib/python2.6/site-packages/pymc/utils.py", line 14, in <module>
    from . import flib
ImportError: dlopen(/Users/aaronmeurer/anaconda/envs/_test/lib/python2.6/site-packages/pymc/flib.so, 2): Symbol not found: ___addtf3
  Referenced from: /Users/aaronmeurer/anaconda/envs/_test/lib/python2.6/site-packages/pymc/flib.so
  Expected in: /usr/lib/libSystem.B.dylib

```

**Comment by asmeurer** [comment]
@fonnesbeck where is the recipe you used?

**Comment by asmeurer** [comment]
Maybe I'm not linking in enough things

```
$ otool -L ~/anaconda/envs/_test/lib/python2.7/site-packages/pymc/flib.so 
/Users/aaronmeurer/anaconda/envs/_test/lib/python2.7/site-packages/pymc/flib.so:
    /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
    /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1094.0.0)
    @loader_path/../../../libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    @loader_path/../../../libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
```

It wants to use the system libgcc and libquadmath even though it was built with the ones from my gcc package.

**Comment by fonnesbeck** [comment]
@asmeurer I was just using the one currently in the 2.3 branch, with the scipy script you posted above replacing the one in the branch.

**Comment by asmeurer** [comment]
OK I was using the one in the conda-recipes repo. I'll take a look if there are any differences. 

I am also building against my gcc package, and on OS X 10.7, both of which could cause differences between our builds.

**Comment by twiecki** [comment]
@asmeurer Where you able to give this a try with recipe we have on this repo?

**Comment by twiecki** [comment]
Seems like gfortran is installed by the conda `gcc` package:

```
conda install gcc

conda$ which gfortran

/Users/jelleferinga/miniconda/bin/gfortran


conda$ find ~/miniconda/ -name "libgfortran.dylib"

/Users/jelleferinga/miniconda//lib/libgfortran.dylib

/Users/jelleferinga/miniconda//pkgs/gcc-4.8.2-4/lib/libgfortran.dylib
```

**Comment by asmeurer** [comment]
`conda package -w` will also tell you that.

I plan to split out the libs from my gcc package soon, at least for Linux.

**Comment by twiecki** [comment]
@asmeurer Did you have a chance to give this another try (compiling the conda recipe that's in this repo) or is there some progress on the fortran libraries in conda? Would be great to make this available!

**Comment by iDrDex** [comment]
@asmeurer I agree with @twiecki that it would be great for me to easily import pymc on OS X Yosemite.

**Comment by asmeurer** [comment]
I think the thing that needs to be done is to take my `gcc` package and extract the dylibs that pymc links to into a separate `libgcc` package, which would be a runtime dependency. We would ideally include this package in the Continuum repos.

**Comment by iDrDex** [comment]
I can confirm that I got it to install on Anaconda Yosemite with:

conda install -c asmeurer pymc

Thx @asmeurer!

**Comment by asmeurer** [comment]
Yes, that should work. The issue is that it will be a very large download because it currently depends on the entire gcc package.

**Comment by jonsedar** [comment]
Thought I should chip in with my 2p:

I'm running OSX Yosemite (10.10) and have an Anaconda Python 3.4.2 env that I'm intending to use for some work in pymc 2.3.

My first attempt was to install and build `gcc-4.9.2_1` via `brew install gcc`, and then install `pymc 2.3.4-np18py34_0 fonnesbeck` using `conda install -c fonnesbeck pymc`

In a ipython session I then `import pymc` and receive an error:

`ImportError: dlopen(/Users/jon/anaconda/envs/price_modelling/lib/python3.4/site-packages/pymc/flib.so, 2): Library not loaded: /usr/local/lib/gcc/x86_64-apple-darwin13.3.0/4.9.1/libquadmath.0.dylib
  Referenced from: /Users/jon/anaconda/envs/price_modelling/lib/python3.4/site-packages/pymc/flib.so
  Reason: image not found`

So before diving into some potential fun with gcc etc, I thought I'd uninstall pymc and try asmeurer's build `conda install -c asmeurer pymc`, which seems to install and import happily, and I've run `pymc.tests.test()` getting 1 minor failure out of 187 runs.

I'll report back with any subtle issues, but so far, thanks for all your help!

**Comment by twiecki** [comment]
Yeah, I think @asmeurer's package works fine. @asmeurer any time line on when this could get included in anaconda?

**Comment by twiecki** [comment]
I think a package with a larger download is better than no package.

**Comment by erwindassen** [comment]
Humm... I've read the whole thread (quite a learning!) and in the end I've tried @asmeurer package. It installed gcc and pymc but after the first import I get the now all to familiar dlopen error: I'm running on Yosemite with Python 3.4.2 (Anaconda 3.7.3).

```
In [1]: import pymc
/Applications/anaconda/lib/python3.4/importlib/_bootstrap.py:321: RuntimeWarning: compiletime version 3.3 of module 'pymc.Container_values' does not match runtime version 3.4
  return f(*args, **kwds)
/Applications/anaconda/lib/python3.4/importlib/_bootstrap.py:321: RuntimeWarning: compiletime version 3.3 of module 'pymc.LazyFunction' does not match runtime version 3.4
  return f(*args, **kwds)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5f262cfcb99b> in <module>()
----> 1 import pymc

/Applications/anaconda/lib/python3.4/site-packages/pymc-2.3.4-py3.3-macosx-10.5-x86_64.egg/pymc/__init__.py in <module>()
     28 from .PyMCObjects import *
     29 from .InstantiationDecorators import *
---> 30 from .CommonDeterministics import *
     31 from .NumpyDeterministics import *
     32 from .distributions import *

/Applications/anaconda/lib/python3.4/site-packages/pymc-2.3.4-py3.3-macosx-10.5-x86_64.egg/pymc/CommonDeterministics.py in <module>()
     19 import inspect
     20 import types
---> 21 from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
     22 from copy import copy
     23 import sys

/Applications/anaconda/lib/python3.4/site-packages/pymc-2.3.4-py3.3-macosx-10.5-x86_64.egg/pymc/utils.py in <module>()
     12 from copy import copy
     13 from .PyMCObjects import Variable
---> 14 from . import flib
     15 import pdb
     16 from numpy.linalg.linalg import LinAlgError

ImportError: dlopen(/Applications/anaconda/lib/python3.4/site-packages/pymc-2.3.4-py3.3-macosx-10.5-x86_64.egg/pymc/flib.so, 2): Library not loaded: /usr/local/lib/gcc/x86_64-apple-darwin13.3.0/4.9.1/libgfortran.3.dylib
  Referenced from: /Applications/anaconda/lib/python3.4/site-packages/pymc-2.3.4-py3.3-macosx-10.5-x86_64.egg/pymc/flib.so
  Reason: image not found
```

As you can see it is trying to load the _inexistent_ local `flib.so`. Something else I'm missing?

**Comment by asmeurer** [comment]
Can you show me the output of `otool -L /Applications/anaconda/lib/python3.4/site-packages/pymc-2.3.4-py3.3-macosx-10.5-x86_64.egg/pymc/flib.so`?

**Comment by erwindassen** [comment]
Below is the output. By the way did you consider linking it against the Accelerate framework in OSX? It has a tuned implementation of the BLAS/Linpack (no need for GCC) but for libquadmath I'm clueless except for this: http://stackoverflow.com/questions/17590525/correct-way-to-statically-link-in-gfortran-libraries-on-osx.

Thanks for the support!

Output:

```
/Applications/anaconda/lib/python3.4/site-packages/pymc-2.3.4-py3.3-macosx-10.5-x86_64.egg/pymc/flib.so:
    /usr/local/lib/gcc/x86_64-apple-darwin13.3.0/4.9.1/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
    /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
    /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 283.0.0)
    /usr/local/Cellar/gcc/4.9.1/lib/gcc/x86_64-apple-darwin13.3.0/4.9.1/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/local/lib/gcc/x86_64-apple-darwin13.3.0/4.9.1/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

Notice that my `/usr/local` dir only has `bin` and `lib` subdirs and both are empty! I once installed gfortran there but since trying to use asmeurer's package I removed it (following gfortran's site own instructions which amounted to `rm -r` the binary and the libs in the aforementioned dirs).

**Comment by asmeurer** [comment]
And this is the latest build of my package (what is `conda list -e`)?

As for using Accelerate, I don't know how to do it, but I agree that it's better. We build the Continuum numpy/scipy against the Accelerate framework on OS X.

**Comment by erwindassen** [comment]
I assumed it is the latest as I installed with as shown in the previous post by _jonsedar_. Here are the versions: 

`gcc=4.8.2=4`
`pymc=2.3.3=np19py34_2`.

**Comment by asmeurer** [comment]
That looks right. I'm not sure what's going on. Does `conda install -f gcc pymc` fix it?

**Comment by erwindassen** [comment]
No, I get the **same** error but this time I also got this:

```
/Applications/anaconda/lib/python3.4/importlib/_bootstrap.py:321: RuntimeWarning: compiletime version 3.3 of module 'pymc.Container_values' does not match runtime version 3.4
  return f(*args, **kwds)
/Applications/anaconda/lib/python3.4/importlib/_bootstrap.py:321: RuntimeWarning: compiletime version 3.3 of module 'pymc.LazyFunction' does not match runtime version 3.4
  return f(*args, **kwds)
```

By the way, does the output of my otool look right?

Cheers,

**Comment by ilanschnell** [comment]
I managed to link pymc statically against libgfortran on MacOSX.  Basically by adding the following to the conda recipe:

```
FCFLAGS=$CFLAGS
cp /usr/local/lib/libgfortran*.*a .
LDFLAGS="-undefined dynamic_lookup -bundle -Wl,-search_paths_first -L$(pwd) $LDFLAGS"
```

PyMC is now officially supported by Anaconda on Linux and Mac OS X!  Conda packages are available for Python 2.

**Comment by cdagnino** [comment]
Great! I just installed `pymc 2.3.4` with `conda install pymc` and run the tests without issue on a Mac OS

**Comment by twiecki** [comment]
@ilanschnell Thanks so much for looking into that!

What about Python 3 and Windows? Those should be pretty easy to add I think.

**Comment by ilanschnell** [comment]
Python 3 packages are also already available for Linux and MacOSX.  We haven't looked into Windows yet, but it's on our list.

**Comment by twiecki** [comment]
Cool! FWIW I think the recipe we have works pretty well:
https://github.com/pymc-devs/pymc/blob/2.3/conda/bld.bat

Not sure if it successfully links in gfortran though.

**Comment by twiecki** [comment]
@ilanschnell Any update on a windows version? I think then we can close this issue and just advertise conda as the preferred way to install pymc!

**Comment by ilanschnell** [comment]
I've just created Windows conda packages for pymc, such that we now support pymc on all platforms and for all Python versions!

**Comment by twiecki** [comment]
@ilanschnell @asmeurer Thank you guys so much! :+1:

**Comment by twiecki** [comment]
Can the recipe to build them all be found anywhere?

**Comment by twiecki** [comment]
@tobeplugged You were extremely helpful in building OSX conda packages for HDDM before. Do you think I could ask you to help with this once more? Specifically, kabuki and hddm would need to be pulled and then `conda build conda`. Of course, no worries if you can't do that.

**Comment by existeundelta** [comment]
Hi, i'm getting this error:

```
 1 import pymc as pm

/anaconda/lib/python2.7/site-packages/pymc-2.3.4-py2.7-macosx-10.9-x86_64.egg/pymc/__init__.pyc in <module>()
     28 from .PyMCObjects import *
     29 from .InstantiationDecorators import *
---> 30 from .CommonDeterministics import *
     31 from .NumpyDeterministics import *
     32 from .distributions import *

anaconda/lib/python2.7/site-packages/pymc-2.3.4-py2.7-macosx-10.9-x86_64.egg/pymc/CommonDeterministics.py in <module>()
     11 __docformat__ = 'reStructuredText'
     12 
---> 13 from . import PyMCObjects as pm
     14 from .Node import Variable
     15 from .Container import Container

ImportError: cannot import name PyMCObjects
```

I think I've tried all, but may be I did something wrong, can you help me? thanks
