### ISSUE TITLE
DOC: Plot Posterior Predictive GLM in 5.0.1?

### ISSUE THREAD

**Issue by tytrzecki** [pymc-devs/pymc#6446]
### Idea or request for content:

I apologize if this is the wrong place to raise this issue, but I am trying to recreate the GLM example in the PyMC3 documentation where the posterior predictive regressions are plotted using:

`plot_posterior_predictive_glm(trace, samples=100, label="posterior predictive regression lines")
`

I haven't found anything in PyMC or arviz that seems to accomplish the same idea. The closest I have found is `plot_ppc()` but it requires that the sample returns the "posterior predictive" group. 

I apologize if I am missing something simple any help is appreciated!

**Comment by michaelosthege** [comment]
According to [the commit message that removed it](https://github.com/pymc-devs/pymc/commit/cf95a787a48d88b4f436ded0adb1d5f02766ae35) you should use [`arviz.plot_lm`](https://python.arviz.org/en/latest/examples/plot_lm.html)

**Comment by michaelosthege** [comment]
The function was rather short, so you could also take inspiration from its latest implementation before it was removed: https://github.com/pymc-devs/pymc/blob/c2008026e869a2545bb3b93d6565a16f94ef30b6/pymc/plots/posteriorplot.py

**Comment by michaelosthege** [comment]
Maybe - can you post a short code example and traceback?

(Closing this already since the original problem is now solved.)

**Comment by tytrzecki** [comment]
Of course. The code is just an adapted version of the PyMC3 GLM example in the docs [here](https://docs.pymc.io/en/v3/pymc-examples/examples/generalized_linear_models/GLM-linear.html).

```
import arviz as az
import bambi as bmb
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pymc as pm

print(f"Running on PyMC v{pm.__version__}")
```
```
RANDOM_SEED = 8927
rng = np.random.default_rng(RANDOM_SEED)

%config InlineBackend.figure_format = 'retina'
az.style.use("arviz-darkgrid")
```
```
size = 200
true_intercept = 1
true_slope = 2

x = np.linspace(0, 1, size)
# y = a + b*x
true_regression_line = true_intercept + true_slope * x
# add noise
y = true_regression_line + rng.normal(scale=0.5, size=size)

data = pd.DataFrame(dict(x=x, y=y))
```
```
fig = plt.figure(figsize=(7, 7))
ax = fig.add_subplot(111, xlabel="x", ylabel="y", title="Generated data and underlying model")
ax.plot(x, y, "x", label="sampled data")
ax.plot(x, true_regression_line, label="true regression line", lw=2.0)
plt.legend(loc=0);
```
```
with pm.Model() as model:  # model specifications in PyMC3 are wrapped in a with-statement
    # Define priors
    sigma = pm.HalfCauchy("sigma", beta=10, testval=1.0)
    intercept = pm.Normal("Intercept", 0, sigma=20)
    x_coeff = pm.Normal("x", 0, sigma=20)

    # Define likelihood
    likelihood = pm.Normal("y", mu=intercept + x_coeff * x, sigma=sigma, observed=y)

    # Inference!
    # draw 3000 posterior samples using NUTS sampling
    trace = pm.sample(3000, return_inferencedata=True)
```
`az.plot_lm(y,idata=trace)`

ValueError                                Traceback (most recent call last)
Cell In[13], line 1
----> 1 az.plot_lm(y,idata=trace)

File ~\anaconda3\envs\pymc5\Lib\site-packages\arviz\plots\lmplot.py:271, in plot_lm(y, idata, x, y_model, y_hat, num_samples, kind_pp, kind_model, xjitter, plot_dim, backend, y_kwargs, y_hat_plot_kwargs, y_hat_fill_kwargs, y_model_plot_kwargs, y_model_fill_kwargs, y_model_mean_kwargs, backend_kwargs, show, figsize, textsize, axes, legend, grid)
    269 len_x = len(x)
    270 length_plotters = len_x * len_y
--> 271 y = np.tile(y, (len_x, 1))
    272 x = np.tile(x, (len_y, 1))
    274 # Filter out the required values to generate plotters

File <__array_function__ internals>:200, in tile(*args, **kwargs)

File ~\anaconda3\envs\pymc5\Lib\site-packages\numpy\lib\shape_base.py:1270, in tile(A, reps)
   1266     return _nx.array(A, copy=True, subok=True, ndmin=d)
   1267 else:
   1268     # Note that no copy of zero-sized arrays is made. However since they
   1269     # have no data there is no risk of an inadvertent overwrite.
-> 1270     c = _nx.array(A, copy=False, subok=True, ndmin=d)
   1271 if (d < c.ndim):
   1272     tup = (1,)*(c.ndim-d) + tup

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 4) + inhomogeneous part.

**Comment by michaelosthege** [comment]
I think you should pass the _name_ of the likelihood variable `"y"` instead of the NumPy array containing observed values.

Try `az.plot_lm(idata=trace, y="y")`

**Comment by tytrzecki** [comment]
I am still getting the same error. Which seems weird because when I call shape on what I believe the plot function is accessing:

`trace['observed_data']['y'].shape
`
It returns (200,)

**Comment by tytrzecki** [comment]
I also just tried to run the example in the az.plot_lm docs and got the same error. I'm curious if it is working for others then maybe it is a numpy version issue.

```
import arviz as az
import numpy as np
import xarray as xr

idata = az.load_arviz_data('regression1d')
x = xr.DataArray(np.linspace(0, 1, 100))
idata.posterior["y_model"] = idata.posterior["intercept"] + idata.posterior["slope"]*x
az.plot_lm(idata=idata, y="y", x=x)
```
```
ValueError                                Traceback (most recent call last)
Cell In[26], line 8
      6 x = xr.DataArray(np.linspace(0, 1, 100))
      7 idata.posterior["y_model"] = idata.posterior["intercept"] + idata.posterior["slope"]*x
----> 8 az.plot_lm(idata=idata, y="y", x=x)

File ~\anaconda3\envs\pymc5\Lib\site-packages\arviz\plots\lmplot.py:271, in plot_lm(y, idata, x, y_model, y_hat, num_samples, kind_pp, kind_model, xjitter, plot_dim, backend, y_kwargs, y_hat_plot_kwargs, y_hat_fill_kwargs, y_model_plot_kwargs, y_model_fill_kwargs, y_model_mean_kwargs, backend_kwargs, show, figsize, textsize, axes, legend, grid)
    269 len_x = len(x)
    270 length_plotters = len_x * len_y
--> 271 y = np.tile(y, (len_x, 1))
    272 x = np.tile(x, (len_y, 1))
    274 # Filter out the required values to generate plotters

File <__array_function__ internals>:200, in tile(*args, **kwargs)

File ~\anaconda3\envs\pymc5\Lib\site-packages\numpy\lib\shape_base.py:1270, in tile(A, reps)
   1266     return _nx.array(A, copy=True, subok=True, ndmin=d)
   1267 else:
   1268     # Note that no copy of zero-sized arrays is made. However since they
   1269     # have no data there is no risk of an inadvertent overwrite.
-> 1270     c = _nx.array(A, copy=False, subok=True, ndmin=d)
   1271 if (d < c.ndim):
   1272     tup = (1,)*(c.ndim-d) + tup

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 4) + inhomogeneous part.
```
