### ISSUE TITLE
Running multiple chains causes RecursionError

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#879]
Setting the `njobs` parameter to run multiple chains results in an error:

```
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-59-548e16bedce3> in <module>()
      6 
      7 
----> 8     trace = sample(5000, njobs=2)

/Users/fonnescj/Github/pymc3/pymc3/sampling.py in sample(draws, step, start, trace, chain, njobs, tune, progressbar, model, random_seed)
    153         sample_args = [draws, step, start, trace, chain,
    154                        tune, progressbar, model, random_seed]
--> 155     return sample_func(*sample_args)
    156 
    157 

/Users/fonnescj/Github/pymc3/pymc3/sampling.py in _mp_sample(njobs, args)
    274 def _mp_sample(njobs, args):
    275     p = mp.Pool(njobs)
--> 276     traces = p.map(argsample, args)
    277     p.close()
    278     return merge_traces(traces)

/Users/fonnescj/anaconda3/lib/python3.5/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    258         in a list that is returned.
    259         '''
--> 260         return self._map_async(func, iterable, mapstar, chunksize).get()
    261 
    262     def starmap(self, func, iterable, chunksize=None):

/Users/fonnescj/anaconda3/lib/python3.5/multiprocessing/pool.py in get(self, timeout)
    606             return self._value
    607         else:
--> 608             raise self._value
    609 
    610     def _set(self, i, obj):

/Users/fonnescj/anaconda3/lib/python3.5/multiprocessing/pool.py in _handle_tasks(taskqueue, put, outqueue, pool, cache)
    383                         break
    384                     try:
--> 385                         put(task)
    386                     except Exception as e:
    387                         job, ind = task[:2]

/Users/fonnescj/anaconda3/lib/python3.5/multiprocessing/connection.py in send(self, obj)
    204         self._check_closed()
    205         self._check_writable()
--> 206         self._send_bytes(ForkingPickler.dumps(obj))
    207 
    208     def recv_bytes(self, maxlength=None):

/Users/fonnescj/anaconda3/lib/python3.5/multiprocessing/reduction.py in dumps(cls, obj, protocol)
     48     def dumps(cls, obj, protocol=None):
     49         buf = io.BytesIO()
---> 50         cls(buf, protocol).dump(obj)
     51         return buf.getbuffer()
     52 

RecursionError: maximum recursion depth exceeded
```

**Comment by twiecki** [comment]
Ran into the same issue.

**Comment by twiecki** [comment]
It seems to work for simpler models, but the stochastic volatility model I can only run with njobs=2, but it breaks with njobs=4. So odd.

**Comment by twiecki** [comment]
Can you try if https://github.com/pymc-devs/pymc3/commit/e873d6d728370b139b24d95e2c2a60d016589e0d fixes it?

**Comment by fonnesbeck** [comment]
Well, I get a _different_ error, so that's progress.

```
MaybeEncodingError: Error sending result: '[<MultiTrace: 1 chains, 40000 iterations, 9 variables>]'. Reason: 'error("'i' format requires -2147483648 <= number <= 2147483647",)'
```

**Comment by twiecki** [comment]
And what a specific error it is. `MaybeEncodingErrorMaybeNot`

**Comment by fonnesbeck** [comment]
Yeah, that seemed odd -- creating an Exception subclass for an error that you're not totally sure about.

**Comment by twiecki** [comment]
Anyway, it looks like we're passing maybe an object where an int is expected?

**Comment by hvasbath** [comment]
You can somewhat hack this with sys.setrecursionlimit(2000), but this also works up to a certain amount of parameters. With my latest model around 450 parameters it doesnt help. As I really need the parallel implementation to work otherwise my model has to run for monthes, I would want to look into this. Can you point me to some code lines where I could start looking- as I am not so familiar yet with the code base. Thank you!

**Comment by hvasbath** [comment]
With increasing the recursion limit and the latest commit from twiecki above( e873d6d ) I get this error. It keeps running doing nothing. Does anybody have any advice where I could start investigating?

Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 319, in _handle_tasks
    put(task)
SystemError: NULL result without error in PyObject_Call

**Comment by fonnesbeck** [comment]
All of the multiprocessing business for PyMC3 is in the `sampling` module. Its pretty basic mapping of processes to the elements of a multiprocessing `Pool`. We might want to explore using `ipyparallel` for parallel processing.

**Comment by twiecki** [comment]
I have also considered switching. The issue is that currently you can't launch processes internally (see https://github.com/ipython/ipyparallel/issues/22 for a plan to change that).

**Comment by fonnesbeck** [comment]
That should not be a deal-breaker. Forcing the user to spin up `ipcluster` is not particularly onerous, particularly if you are working in Jupyter, where it is just a tab in the interface. I think its a small price to pay for more robust parallelism, and if it gets automated in the future, all the better.

**Comment by datnamer** [comment]
What about Dask?

**Comment by fonnesbeck** [comment]
Would Dask be effective here? I could see if we were applying the same algorithm  to subsets of a dataset, but a set of parallel chains executes over the entire dataset for each chain. So, its not clear how Dask's collections would be beneficial. That said, it may be useful if we ever implement expectation propagation, which does subdivide the data.

**Comment by datnamer** [comment]
Dask imperative + multiprocessing scheduler can schedule the chains without needing to use a specific collection to chunk.  

But this is out of my depth. 

Maybe @mrocklin can chime in.

**Comment by twiecki** [comment]
I don't think Dask, although awesome, can be leveraged here.

**Comment by mrocklin** [comment]
If someone can briefly describe the problem I'd be happy to chime in if there is potential overlap.  The dask schedulers are useful well outside the common use case of big chunked arrays.  If you're considering technologies like multiprocessing or ipyparallel it's possible that one of the dask schedulers could be relevant.

**Comment by fonnesbeck** [comment]
@mrocklin Matt, this is Monte Carlo sampling for Bayesian statistical modeling. Its an embarrassingly parallel task that just simulates Markov chains using the same model on the same dataset, then uses the sampled chains (the output of the algorithm) for inference. We are currently using the multiprocessing module for this, but are contemplating a move to something more robust.

**Comment by mrocklin** [comment]
Something non-trivial must be going on to cause multiprocessing to hang.

Looking at the traceback it seems like you might be trying to send something that `pickle` doesn't like?  Historically I've gotten around this by pre-serializing everything with dill or cloudpickle before I hand things off to `multiprocessing`.  This is what `dask.multiprocessing.get` does.  

If this is what is going on then the [`pathos`](https://pypi.python.org/pypi/pathos) library would probably be a decent drop in replacement for you all.  It's a `multiprocessing` clone that uses `dill`.

But really, I'm just guessing at the problem that you're trying to solve and so am probably out of my depth here.  Happy to help if I can.  Best of luck.

**Comment by fonnesbeck** [comment]
Thanks, Matt. Unfortunately `pathos` appears not to support Python 3 yet, so I will look at explicitly passing everything to `dill`.

**Comment by mrocklin** [comment]
I write a function like the following:

``` python
def apply(serialized_func, serialized_args, serialized_kwargs):
    func = dill.loads(serialized_func)
    args = dill.loads(serialized_args)
    kwargs = dill.loads(serialized_kwargs)
```

And then I dumps my func, args, kwargs ahead of time and call them with the apply function remotely.  Something like the following:

``` python
pool.map(apply, [dill.dumps(func) for i in range(len(sequence))], [dill.dumps(args) for args in sequence])
```

`<self serving>` Or, you can always just use `dask.multiprocessing.get`, where this work is already done. `</self serving>`

**Comment by fonnesbeck** [comment]
I might have found a solution using Joblib, but will give this a shot if that doesn't work. Thanks again.

**Comment by mrocklin** [comment]
Oh great.  That's much simpler.

**Comment by tyarkoni** [comment]
I don't think this solves the problem, unfortunately... On the joblib branch, with njobs=4 and a pretty big model, I still get a max recursion exceeded exception (see below). On inspection, it looks like Joblib uses multiprocessing as its default backend, so I guess that makes sense. I tried switching to the threading backend, but that failed with a different set of errors. 

```
Traceback (most recent call last):
  File "run_wm.py", line 53, in <module>
    run_model(40)
  File "run_wm.py", line 40, in run_model
    trace = model.run(samples=250, verbose=True, find_map=False, njobs=4)
  File "/Users/tal/Dropbox/Projects/RandomStimuli/code/pymcwrap/pymcwrap/model.py", line 383, in run
    samples, start=start, step=step, progressbar=verbose, njobs=njobs)
  File "/usr/local/lib/python3.5/site-packages/pymc3-3.0-py3.5.egg/pymc3/sampling.py", line 146, in sample
    return sample_func(**sample_args)
  File "/usr/local/lib/python3.5/site-packages/pymc3-3.0-py3.5.egg/pymc3/sampling.py", line 272, in _mp_sample
    **kwargs) for i in range(njobs))
  File "/usr/local/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/parallel.py", line 810, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/parallel.py", line 727, in retrieve
    self._output.extend(job.get())
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 385, in _handle_tasks
    put(task)
  File "/usr/local/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 368, in send
    CustomizablePickler(buffer, self._reducers).dump(obj)
RecursionError: maximum recursion depth exceeded
```

**Comment by fonnesbeck** [comment]
It was worth a shot. I will try flavoring it with a little `dill`.

**Comment by fonnesbeck** [comment]
Actually, `joblib` serializes the arguments for us, so that's not the solution. Increasing the recursion limit helps (as @eigenblutwurst notes), which I have done inside `sample`. This problem may resurface with bigger models. Works well on the rugby analytics example (which I have modified) using 4 cores.

**Comment by twiecki** [comment]
https://github.com/joblib/joblib/pull/240

**Comment by fonnesbeck** [comment]
@twiecki nice find! I will try using the joblib from master and see if that does the trick without boosting recursion limits.

**Comment by fonnesbeck** [comment]
Unfortunately, `dill` does not save the day. Still hits the recursion limit. My last commit to the branch boosts it to 10000, which may be sufficient for models of a certain size.

**Comment by tyarkoni** [comment]
My model has ~1,000 parameters, and still fails with a recursion limit of 10,000. Not the end of the world in this case, as it runs tolerably with one process and converges quickly. But would be nice to have this work at some point.

Do you know off-hand where the recursion is happening? I'm guessing it's in the Model or MultiTrace. It would be a bit of work, but a reasonable way forward might be to implement a `__reduce__` method on the problem class that replaces object references with hashed IDs, and then reconstructs the references on deserialization. If you can give me some pointers as to where the recursion is happening, I can take a crack at this next time I have some free time.

**Comment by fonnesbeck** [comment]
I assumed it had something to do with the Theano model building its graph, so somewhere in the Model. That would explain why it happens with high-dimensional model, but I am just guessing. Maybe @jsalvatier has ideas.

**Comment by tyarkoni** [comment]
Oh, that makes sense. And it look like it's come up several times before on the Theano repo:

https://github.com/Theano/Theano/issues/1795
https://github.com/Theano/Theano/issues/3341
https://github.com/Theano/Theano/issues/3607

Guess I'll stick with raising the recursion limit even further and hoping for the best. :)

**Comment by hvasbath** [comment]
I dont think its the theano graph. Otherwise it would crash already during compilation. Wouldnt it?
After increasing the recursion limit I get the error message above. Which I cannot interprete at all.
Anyway its nice that so many people started looking into it :) .

**Comment by fonnesbeck** [comment]
I am just guessing at plausible explanations. I've tried changing up the trace, both by drastically reducing the number of samples, and by using text or sqlite backends, but these both result in the same error.

The failure is triggered during serialization dumps, both under Joblib and plain `multiprocessing`.

**Comment by fonnesbeck** [comment]
I can hit the recursion error without using multiprocessing:

https://gist.github.com/f2da55c0e2f6d8f35a25

so I'm pretty convinced this is related to the depth of the computational graph.

**Comment by fonnesbeck** [comment]
The example above is pretty worrying because it is a small model (albeit with a large variance-covariance matrix). It will be important to see if we are just being inefficient in PyMC about specifying the model graph, or if this is a limitation of Theano.

**Comment by hvasbath** [comment]
But you have two nested for loops, which are very inefficient to be used in theano. Did you check with profiling how many apply nodes you create with this? If this reaches a couple of thousand it will crash.
By using scan you can significantly reduce this number of nodes. With the recent bleeding edge theano version scan became really fast.
In total I have 2 times, two nested scans in my quite complex model and I do not get the recursion error anymore. The error I get is above something in threading...

**Comment by hvasbath** [comment]
Also you are applying a numpy operation np.exp on a theano tensor your HalfCauchy distributions. Or is this not a tensor?

**Comment by fonnesbeck** [comment]
Good catch on the exponential. I was using list compressions because I was looping over data. Should I be using shared variables instead with `scan`?

**Comment by fonnesbeck** [comment]
Or I could just do [this](https://gist.github.com/3919968669ecd852f87f), and avoid the issue altogether!

**Comment by twiecki** [comment]
@fonnesbeck can you elaborate?

**Comment by fonnesbeck** [comment]
In the squared exponential, I can calculate the covariance matrix without looping, simply by multiplying the distance matrix by scalars. So this side-steps the problem of doing Python loops with Theano variables. This was creating a huge computational graph that caused the recursion depth issue.

**Comment by twiecki** [comment]
Cool! A GP example would be a great addition :).

**Comment by hvasbath** [comment]
Good job simplifying it! Thats nice. But if you cant- exactly shared variables and scan would be the way to go for any loop which is long. If you have a loop that creates few hundred apply nodes it is still fine to use for, but as soon it goes into thousand you will face problems- either with horribly long optimization time, or recursion errors ;) .

**Comment by fonnesbeck** [comment]
The only problem is -- the model gives completely incorrect answers! I've [updated the notebook](https://gist.github.com/3919968669ecd852f87f) to include the same model run under Stan, and you can see that PyMC3 goes off the rails. 

EDIT: it would help if I parameterized it correctly! Forgot that we use the inverse covariance on `MvNormal`. The results are very close to Stan's implementation now, though ours does not seem to mix as well.

**Comment by twiecki** [comment]
@fonnesbeck This is awesome, code is also so much more elegant and readable than the STAN version. Would be fun to try with the recently fixed ADVI.

**Comment by twiecki** [comment]
That works quite well indeed 
![image](https://cloud.githubusercontent.com/assets/674200/13198324/24f9fba2-d806-11e5-8776-cd3825ea4d0a.png)

**Comment by fonnesbeck** [comment]
Those are with ADVI?

This issue has gone down a rabbit hole, but it should be easy to automate a lot of the GP building.

**Comment by jsalvatier** [comment]
A very productive rabbit hole it seems.

**Comment by jonsedar** [comment]
I've also run into this quite often. Thought I'd create a minimum reproducible example in case anyone wants to use it for testing etc, it's very basic linear regression: https://gist.github.com/jonsedar/b68136b53ee43465ecc9

**Comment by hvasbath** [comment]
Probably the problems occur because of the forking of the process as reported here:
https://pythonhosted.org/joblib/parallel.html
Bad interaction of multiprocessing and third-party libraries¶
One solution could be to use spawning instead for python 3.4 and above. However I am using 2.7 so there we would need another solution. One is suggested here https://github.com/Theano/Theano/wiki/Using-Multiple-GPUs for forking GPU processes.
Propably this could be used for CPUs as well?

**Comment by fonnesbeck** [comment]
Thanks for the info. I've tried setting `JOBLIB_START_METHOD='forkserver'` which works in the sense of preventing a crash, but I start to see other errors:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fonnescj/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Users/fonnescj/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/fonnescj/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/joblib/pool.py", line 359, in get
    return recv()
  File "/Users/fonnescj/anaconda3/lib/python3.5/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
  File "/Users/fonnescj/Repositories/pymc3/pymc3/distributions/distribution.py", line 18, in __new__
    raise TypeError("No model on context stack, which is needed to "
TypeError: No model on context stack, which is needed to use the Normal('x', 0,1) syntax. Add a 'with model:' block
Process ForkServerPoolWorker-3:
Traceback (most recent call last):
  File "/Users/fonnescj/Repositories/pymc3/pymc3/model.py", line 113, in get_context
    return cls.get_contexts()[-1]
IndexError: list index out of range
```

I will read up on Theano's strategy as well. We really ought to get GPU multiprocessing going, however. Seems like low-hanging fruit.

**Comment by hvasbath** [comment]
One other thing that I noticed at least with the Text backend, which is a problem.
backend = Text(name,model)
initialises the backend object with the target folder in backend.name and the respective .csv file path in backend.filename (after backend.setup)
where .df contains then the sampled trace values, after running sample like:
trace = sample(draws,step,...)
Now the BIG BIG BUT:
The returned "trace" is still referring to the backend instance. With .df and .filename.
If you do backend.df=None your trace.df will be None as well.
Thats ok if you just run one chain. But if you run several chains especially when doing it serial each MultiTrace object is related to backend, because backend.setup(draws, chainnumber) only opens the csv file on disk but does not copy the backend basetrace object. So before each "sample" you need to reinitiallise the backend, instead of only doing repeated times backend.setup which is being done in _sample.
Somehow in backend.setup the whole object needs to be copied. But I have no idea how to do this.

I just noticed it, because I wanted to run "sample" several times in a loop and collect all the traces in a list. Turns out all the traces had the same values. 
But on disk they are properly written. Then when loading the traces from disk the traces are properly loaded into several objects.

I have no idea about the other backends sqlite and ndarray.
Apparently thats the issue with sqlite as well:
https://github.com/pymc-devs/pymc3/issues/1008

**Comment by grburgess** [comment]
I just updated to the latest Theano 0.8 and pymc3 and this problem has disappeared for me. 
Strange thing though, while I build python manually with setup.py install, it still complained that it wanted Theano 0.7. The install seemed to go ok though.

**Comment by hvasbath** [comment]
yes for me it also wants to install theano 0.7 although I have the dev version thats somehow anoying, I simply disabled it in the setup script, although there must be a nice way.

**Comment by twiecki** [comment]
It's trying to pull 0.7 when you run pymc3's setup.py?

**Comment by hvasbath** [comment]
Yes it does.

**Comment by grburgess** [comment]
Yes, it seemed to install fine and use Theano 0.8, but it was rather confusing.

**Comment by hvasbath** [comment]
I have to abort it because when I let it install it, my import uses the 0.7 version instead of the dev version. They made sooooo many improvements in the current dev version so it is really significant to use the dev version.

**Comment by twiecki** [comment]
https://github.com/pymc-devs/pymc3/commit/f9de16e78c0116a8236611eeb1e840ecec67f41b should fix that.

**Comment by hvasbath** [comment]
Ah great thx!

**Comment by grburgess** [comment]
Fixed it. thanks!

**Comment by springcoil** [comment]
Is it time to shut this?

**Comment by grburgess** [comment]
I haven't done extensive testing, but on some high dimensional problems that originally threw the recursion error, the problem has disappeared. So perhaps for now it is solved. :)

**Comment by twiecki** [comment]
That sounds amazing. I'll close it but feel free to reopen if the problem persists with master pymc3 and theano.

**Comment by jonsedar** [comment]
Thanks for the recent bugfixes guys, also the updates to the build dependencies mean I'm now running `theano: 0.8.0rc1` and either or both changes seem to have increased the theshold at which I was finding recursion errors.

EDIT: Okay, well - that does seem to have fixed it. I think I have a different bug though: 
1. for a sufficiently complex model, the first time I create and sample it using `njobs > 1`, the processes start (I'm viewing in `htop`) and then they die without throwing an error
2. If I re-run the sampling then the processes seem to run fine.

I assume the difference in 2 is that the model is already cached. It's tricky to replicate though, a bit of a Heisenbug!

**Comment by hvasbath** [comment]
I also still get my segmentation faults - also with creating all the Text backends in advance...

**Comment by vivek-hari** [comment]
Oh! Really. Even with the latest pymc3 version, I am getting the same error with njobs=2. 

**multiprocessing.pool.MaybeEncodingError: Error sending result: '[<MultiTrace: 1 chains, 10 iterations, 2106 variables>]'. Reason: 'RuntimeError('maximum recursion depth exceeded',)'**

```
    trace = pm.sample(n_samples, step=step_func, start=start, njobs=n_chains, progressbar=False)
  File "/home/user/.local/lib/python2.7/site-packages/pymc3/sampling.py", line 150, in sample
    return sample_func(**sample_args)
  File "/home/user/.local/lib/python2.7/site-packages/pymc3/sampling.py", line 282, in _mp_sample
    **kwargs) for i in range(njobs))
  File "/home/user/.local/lib/python2.7/site-packages/joblib/parallel.py", line 810, in __call__
    self.retrieve()
  File "/home/user/.local/lib/python2.7/site-packages/joblib/parallel.py", line 727, in retrieve
    self._output.extend(job.get())
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[<MultiTrace: 1 chains, 10 iterations, 2106 variables>]'. Reason: 'RuntimeError('maximum recursion depth exceeded',)'

```

I have pymc3-3.0, numpy-1.11.0, Theano-0.8.1, scipy-0.17.0 installed.
Anyone else facing the same issue in the latest version of pymc3?

**Comment by fonnesbeck** [comment]
By "latest pymc3 version" do you mean that you installed it from GitHub master? That is,

```
pip install -U git+https://github.com/pymc-devs/pymc3.git
```

**Comment by vivek-hari** [comment]
I installed using

`pip install --process-dependency-links git+https://github.com/pymc-devs/pymc3`

**Comment by fonnesbeck** [comment]
Make sure you use the `-U` flag or it may not update. I have not had this error since we closed this issue, so my first guess is that your update did not stick.

**Comment by vivek-hari** [comment]
Oh.. Thank you so much for your quick response. I'll update using `-U` flag and will get back. Thanks again!

**Comment by vivek-hari** [comment]
Sorry @fonnesbeck , installing pymc3 with -U also leads to same error. 
Even I removed all the packages(pymc3, numpy, scipy, theano) from my machine and tried fresh installation of pymc3 using `pip install -U git+https://github.com/pymc-devs/pymc3.git`. It also ended up in RuntimeError('maximum recursion depth exceeded',).

I have, 
Python 2.7.6, 
pymc3.0, 
matplotlib-1.5.1, joblib-0.9.4,  numpy-1.11.0, pandas-0.18.0,  patsy-0.4.1, pydot_ng-1.0.0, pyparsing-2.1.1,scipy-0.17.0, 
Theano-0.8.1 
installed in my machine.

`nvidia-smi` toolkit gives following details,
 NVIDIA-SMI 346.96, Driver Version: 346.96, 4 GPU(0,1,2,3).

My .theanorc config is,

```
[global]
device = gpu
floatX = float32
assert_no_cpu_op = warn
[cuda]
root = /usr/local/cuda
[nvcc]
fastmath = True
[pycuda]
init = True
```

Is there anything else to be done?

**Comment by twiecki** [comment]
Perhaps the GPU utilization is at fault? Have you tried with CPU?

**Comment by vivek-hari** [comment]
Thanks @twiecki I will try with CPU and post my updates.

**Comment by vivek-hari** [comment]
`device=cpu` in .theanorc  also raises RuntimeError('maximum recursion depth exceeded',).

**Comment by vivek-hari** [comment]
Below snippet is I am trying to execute. 

``` python
import pymc3 as pm
import theano.tensor as T
import pandas

def tinvlogit(x):
    return T.exp(x) / (1 + T.exp(x))

pandas_df = pandas.read_csv("data.csv")

x_col1 = pandas_df['col1']
x_col2 = pandas_df['col2']
x_col3 = pandas_df['col3']
n_col3 = len(pandas_df['col3'].unique())

with pm.Model() as model:
        b_0 = pm.Normal('b_0', mu=0, sd=100)
        b_col1 = pm.Normal('b_col1', mu=0, sd=100)
        b_col2 = pm.Normal('b_col2', mu=0, sd=100)
        sigma_col3 = pm.HalfNormal('sigma_col3', sd=100)
        b_col3 = pm.Normal('b_col3', mu=0, sd=sigma_col3, shape=n_col3)

        for i in range(0, len(pandas_df)):
            p = pm.Deterministic('p', T.maximum(0, T.minimum(1, tinvlogit(
                b_0 + b_col1 * x_col1.at[i] + b_col2 * x_col2.at[i] + b_col3[x_col3.at[i]))))

        y = pm.Bernoulli('y', p, observed=pandas_df.y)

        start = pm.find_MAP()

        step_func = pm.NUTS()

        trace = pm.sample(5000, step=step_func, start=start, njobs=2, progressbar=True)
```

`pm.sample` fails with **`RuntimeError('maximum recursion depth exceeded')`**

`pandas_df` is pandas dataframe with columns col1(decimal), col2(decimal), col3(integer between 1-10), y(0 or 1) and has 50000 rows.

**Comment by hvasbath** [comment]
You get the recursion error because your graph will be very long as your loop will be running for 50k times, each time with all the nodes. Although I dont really get the purpose of your model I have the feeling you could vectorize it and get rid of the loop. The RVs have a shape parameter where you can simply create vectors of length of your data frame.
The way you do it now p will be always overwritten and only the last sample of your dataframe will go into the cost. Or am I missing something?
